openapi: 3.1.0
info:
  title: Internet Golf API
  version: 0.5.0
servers:
- url: /
paths:
  /alive:
    get:
      operationId: get-alive
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get alive
  /deploy/container:
    put:
      operationId: put-deploy-container
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeployContainerInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Put deploy container
  /deploy/files:
    put:
      operationId: put-deploy-files
      requestBody:
        content:
          multipart/form-data:
            encoding:
              contents:
                contentType: "application/gzip,application/octet-stream"
                style: form
              keepLeadingDirectories:
                contentType: text/plain
                style: form
              preserveExistingFiles:
                contentType: text/plain
                style: form
              url:
                contentType: text/plain
                style: form
            schema:
              $ref: "#/components/schemas/put_deploy_files_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Put deploy files
  /deploy/new:
    post:
      operationId: post-deploy-new
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeploymentCreateInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Post deploy new
  /deployment/{url}:
    get:
      operationId: get-deployment-by-url
      parameters:
      - explode: false
        in: path
        name: url
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDeploymentOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get deployment by URL
  /token/generate:
    post:
      operationId: post-token-generate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBearerTokenInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateBearerTokenOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Post token generate
  /user/register:
    put:
      operationId: put-user-register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddExternalUserInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Put user register
components:
  schemas:
    AddExternalUserInputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        externalUserId: externalUserId
        externalUserHandle: externalUserHandle
        externalUserSource: externalUserSource
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        externalUserHandle:
          type: string
        externalUserId:
          type: string
        externalUserSource:
          type: string
      required:
      - externalUserSource
    CreateBearerTokenInputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        fullPermissions: true
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        fullPermissions:
          type: boolean
      required:
      - fullPermissions
    CreateBearerTokenOutputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        token: token
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        token:
          type: string
      required:
      - token
    DeployContainerInputBody:
      additionalProperties: false
      example:
        registryUrl: registryUrl
        internalAppPort: 0
        $schema: https://openapi-generator.tech
        containerName: containerName
        registryAuthToken: registryAuthToken
        url: url
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        containerName:
          type: string
        internalAppPort:
          format: int64
          type: integer
        registryAuthToken:
          type: string
        registryUrl:
          type: string
        url:
          type: string
      required:
      - containerName
      - internalAppPort
      - registryUrl
      - url
    DeploymentCreateInputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        externalSourceType: externalSourceType
        preserveExternalPath: true
        url: url
        externalSource: externalSource
        tags:
        - tags
        - tags
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        externalSource:
          type: string
        externalSourceType:
          type: string
        preserveExternalPath:
          type: boolean
        tags:
          items:
            type: string
          nullable: true
          type: array
        url:
          type: string
      required:
      - url
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: "Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"
          type: string
        message:
          description: Error message text
          type: string
        value: {}
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          nullable: true
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          format: uri
          type: string
        status:
          description: HTTP status code
          format: int64
          type: integer
        title:
          description: "A short, human-readable summary of the problem type. This\
            \ value should not change between occurrences of the error."
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          format: uri
          type: string
    GetDeploymentOutputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        hasContent: true
        externalSourceType: externalSourceType
        preserveExternalPath: true
        servedThing: servedThing
        Url:
          path: path
          domain: domain
        externalSource: externalSource
        servedThingType: servedThingType
        tags:
        - tags
        - tags
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        Url:
          $ref: "#/components/schemas/Url"
        externalSource:
          type: string
        externalSourceType:
          type: string
        hasContent:
          type: boolean
        preserveExternalPath:
          type: boolean
        servedThing:
          type: string
        servedThingType:
          type: string
        tags:
          items:
            type: string
          nullable: true
          type: array
      required:
      - Url
      - hasContent
      - servedThing
      - servedThingType
    HealthCheckOutputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        ok: true
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        ok:
          type: boolean
      required:
      - ok
    SuccessOutputBody:
      additionalProperties: false
      example:
        $schema: https://openapi-generator.tech
        success: true
        message: message
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        message:
          type: string
        success:
          type: boolean
      required:
      - message
      - success
    Url:
      additionalProperties: false
      example:
        path: path
        domain: domain
      properties:
        domain:
          type: string
        path:
          type: string
      required:
      - domain
    put_deploy_files_request:
      properties:
        contents:
          format: binary
          type: string
        keepLeadingDirectories:
          type: boolean
        preserveExistingFiles:
          type: boolean
        url:
          type: string
      required:
      - url
